In [1]:
import numpy as np
import time

# Function to add two large vectors
def vecAdd():
    n = 10000000  # 10 million elements

    # Host input vectors (created using NumPy)
    h_a = np.arange(n, dtype=np.float64)
    h_b = np.arange(n, dtype=np.float64)

    # Start the timer
    start = time.time()

    # Perform vector addition
    h_c = h_a + h_b

    # End the timer
    end = time.time()

    print("First 10 elements of result vector:", h_c[:10])
    print("Time taken for vector addition on CPU:", end - start, "seconds")

# Function to multiply two N x N matrices
def matMul():
    N = 1024  # 1024 x 1024 matrices

    # Host matrices (created using NumPy)
    h_a = np.random.rand(N, N).astype(np.float64)
    h_b = np.random.rand(N, N).astype(np.float64)

    # Start the timer
    start = time.time()

    # Perform matrix multiplication
    h_c = np.matmul(h_a, h_b)

    # End the timer
    end = time.time()

    print("First 5x5 block of result matrix:\n", h_c[:5, :5])
    print("Time taken for matrix multiplication on CPU:", end - start, "seconds")

def main():
    print("Add two large vectors:")
    vecAdd()

    print("\nMultiply two N x N matrices:")
    matMul()

if __name__ == "__main__":
    main()


Add two large vectors:
First 10 elements of result vector: [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
Time taken for vector addition on CPU: 0.03387570381164551 seconds

Multiply two N x N matrices:
First 5x5 block of result matrix:
 [[258.95947163 255.6485858  251.31877175 242.85904212 255.12416088]
 [258.49686028 262.41930434 258.96101969 251.55880749 255.61496989]
 [261.13798815 261.91378037 256.33898807 251.9529689  250.52737796]
 [256.5693612  245.06720887 249.28894068 241.65650297 245.0859975 ]
 [252.12563142 256.13561331 257.18783047 243.68705936 251.32879428]]
Time taken for matrix multiplication on CPU: 0.1261448860168457 seconds
